

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: learningprocess
    volumes:
      - gymdata:/var/lib/postgresql/data

volumes:
  gymdata:
